### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by knopserl** [rocketscream/Low-Power#56]
Is anybody capable and willing to support the ESP32 family?
It has a RTC and ULP CPU so the prerequisites should be there.
I would urgently need a Lowpower library so that I can complete my AskSinPP (Homematic) port for ESP32.

**Comment by milesfrankland** [comment]
https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/DeepSleep

**Comment by knopserl** [comment]
@milesfrankland thanks for the link to the deep sleep samples. I know them of course :-)
However within the AskSinPP clibs/classes which use the LowPower Lib, there would be a lot of changes to "emulate" the LowPowerLib and to do the changes based on the deep sleep ESP32 features. I tought somebody could include the ESP32 support within the LowPower classes to ensure compatibility to all projects using the LowPower lib.

**Comment by rocketscream** [comment]
I'm reluctant to support the ESP32 port due to it's complete different architecture and the way it behaves from waking up from sleep. It requires a pin to wake up (basically resetting the MCU) and everything starts from the setup() again. But, if anyone wants to provide a compatibility layer, feel free to do a pull request.

**Comment by knopserl** [comment]
@rocketscream I can understand. For that reason, I have requested now the nRF52 (832 or 840) support. That should fit to the behavior of the ATMEGAS but with even better sleep features.
BTW: The ESP32 does not really need a wakeup-pin but it has 4 ultra low power timer which wake-up the ESP32 on it's own.
